// Pour convertir le jour en français
const Map<String, String> DAY = {
  "Monday": "Lundi",
  "Tuesday": "Mardi",
  "Wednesday": "Mercredi",
  "Thursday": "Jeudi",
  "Friday": "Vendredi",
  "Saturday": "Samedi",
  "Sunday": "Dimanche",
};

// Pour convertir le mois en français
const Map<String, String> MONTH = {
  "January": "Janvier",
  "February": "Février",
  "March": "Mars",
  "April": "Avril",
  "May": "Mai",
  "June": "Juin",
  "July": "Juillet",
  "August": "Août",
  "September": "Septembre",
  "October": "Octobre",
  "November": "Novembre",
  "December": "Décembre",
};

// Pour convertir le code reçue avec sa signification
const Map<int, String> weatherDescriptions = {
  0: 'Soleil',
  1: 'Peu nuageux',
  2: 'Ciel voilé',
  3: 'Nuageux',
  4: 'Très nuageux',
  5: 'Couvert',
  6: 'Brouillard',
  7: 'Brouillard givrant',
  10: 'Pluie faible',
  11: 'Pluie modérée',
  12: 'Pluie forte',
  13: 'Pluie faible verglaçante',
  14: 'Pluie modérée verglaçante',
  15: 'Pluie forte verglaçante',
  16: 'Bruine',
  20: 'Neige faible',
  21: 'Neige modérée',
  22: 'Neige forte',
  30: 'Pluie et neige mêlées faibles',
  31: 'Pluie et neige mêlées modérées',
  32: 'Pluie et neige mêlées fortes',
  40: 'Averses de pluie locales et faibles',
  41: 'Averses de pluie locales',
  42: 'Averses locales et fortes',
  43: 'Averses de pluie faibles',
  44: 'Averses de pluie',
  45: 'Averses de pluie fortes',
  46: 'Averses de pluie faibles et fréquentes',
  47: 'Averses de pluie fréquentes',
  48: 'Averses de pluie fortes et fréquentes',
  60: 'Averses de neige localisées et faibles',
  61: 'Averses de neige localisées',
  62: 'Averses de neige localisées et fortes',
  63: 'Averses de neige faibles',
  64: 'Averses de neige',
  65: 'Averses de neige fortes',
  66: 'Averses de neige faibles et fréquentes',
  67: 'Averses de neige fréquentes',
  68: 'Averses de neige fortes et fréquentes',
  70: 'Averses de pluie et neige mêlées localisées et faibles',
  71: 'Averses de pluie et neige mêlées localisées',
  72: 'Averses de pluie et neige mêlées localisées et fortes',
  73: 'Averses de pluie et neige mêlées faibles',
  74: 'Averses de pluie et neige mêlées',
  75: 'Averses de pluie et neige mêlées fortes',
  76: 'Averses de pluie et neige mêlées faibles et nombreuses',
  77: 'Averses de pluie et neige mêlées fréquentes',
  78: 'Averses de pluie et neige mêlées fortes et fréquentes',
  100: 'Orages faibles et locaux',
  101: 'Orages locaux',
  102: 'Orages fort et locaux',
  103: 'Orages faibles',
  104: 'Orages',
  105: 'Orages forts',
  106: 'Orages faibles et fréquents',
  107: 'Orages fréquents',
  108: 'Orages forts et fréquents',
  120: 'Orages faibles et locaux de neige ou grésil',
  121: 'Orages locaux de neige ou grésil',
  122: 'Orages locaux de neige ou grésil',
  123: 'Orages faibles de neige ou grésil',
  124: 'Orages de neige ou grésil',
  125: 'Orages de neige ou grésil',
  126: 'Orages faibles et fréquents de neige ou grésil',
  127: 'Orages fréquents de neige ou grésil',
  128: 'Orages fréquents de neige ou grésil',
  130: 'Orages faibles et locaux de pluie et neige mêlées ou grésil',
  131: 'Orages locaux de pluie et neige mêlées ou grésil',
  132: 'Orages fort et locaux de pluie et neige mêlées ou grésil',
  133: 'Orages faibles de pluie et neige mêlées ou grésil',
  134: 'Orages de pluie et neige mêlées ou grésil',
  135: 'Orages forts de pluie et neige mêlées ou grésil',
  136: 'Orages faibles et fréquents de pluie et neige mêlées ou grésil',
  137: 'Orages fréquents de pluie et neige mêlées ou grésil',
  138: 'Orages forts et fréquents de pluie et neige mêlées ou grésil',
  140: 'Pluies orageuses',
  141: 'Pluie et neige mêlées à caractère orageux',
  142: 'Neige à caractère orageux',
  210: 'Pluie faible intermittente',
  211: 'Pluie modérée intermittente',
  212: 'Pluie forte intermittente',
  220: 'Neige faible intermittente',
  221: 'Neige modérée intermittente',
  222: 'Neige forte intermittente',
  230: 'Pluie et neige mêlées',
  231: 'Pluie et neige mêlées',
  232: 'Pluie et neige mêlées',
  235: 'Averses de grêle',
};

// Pour associer le code reçue avec une couleur de l'IU
enum ColorCode {
  SUN,
  SOME_CLOUDS,
  CLOUDS,
  RAIN,
  SNOW,
  THUNDERSTORM,
  HAIL,
  UNKNOW,
}

// Pour regroupé les temps par groupes
const Map<int, ColorCode> weatherCode = {
  0: ColorCode.SUN,

  1: ColorCode.SOME_CLOUDS,
  2: ColorCode.SOME_CLOUDS,

  3: ColorCode.CLOUDS,
  4: ColorCode.CLOUDS,
  5: ColorCode.CLOUDS,
  6: ColorCode.CLOUDS,
  7: ColorCode.CLOUDS,

  10: ColorCode.RAIN,
  11: ColorCode.RAIN,
  12: ColorCode.RAIN,
  13: ColorCode.RAIN,
  14: ColorCode.RAIN,
  15: ColorCode.RAIN,
  16: ColorCode.RAIN,

  20: ColorCode.SNOW,
  21: ColorCode.SNOW,
  22: ColorCode.SNOW,
  30: ColorCode.SNOW,
  31: ColorCode.SNOW,
  32: ColorCode.SNOW,

  40: ColorCode.RAIN,
  41: ColorCode.RAIN,
  42: ColorCode.RAIN,
  43: ColorCode.RAIN,
  44: ColorCode.RAIN,
  45: ColorCode.RAIN,
  46: ColorCode.RAIN,
  47: ColorCode.RAIN,
  48: ColorCode.RAIN,

  60: ColorCode.SNOW,
  61: ColorCode.SNOW,
  62: ColorCode.SNOW,
  63: ColorCode.SNOW,
  64: ColorCode.SNOW,
  65: ColorCode.SNOW,
  66: ColorCode.SNOW,
  67: ColorCode.SNOW,
  68: ColorCode.SNOW,
  70: ColorCode.SNOW,
  71: ColorCode.SNOW,
  72: ColorCode.SNOW,
  73: ColorCode.SNOW,
  74: ColorCode.SNOW,
  75: ColorCode.SNOW,
  76: ColorCode.SNOW,
  77: ColorCode.SNOW,
  78: ColorCode.SNOW,

  100: ColorCode.THUNDERSTORM,
  101: ColorCode.THUNDERSTORM,
  102: ColorCode.THUNDERSTORM,
  103: ColorCode.THUNDERSTORM,
  104: ColorCode.THUNDERSTORM,
  105: ColorCode.THUNDERSTORM,
  106: ColorCode.THUNDERSTORM,
  107: ColorCode.THUNDERSTORM,
  108: ColorCode.THUNDERSTORM,
  120: ColorCode.THUNDERSTORM,
  121: ColorCode.THUNDERSTORM,
  122: ColorCode.THUNDERSTORM,
  123: ColorCode.THUNDERSTORM,
  124: ColorCode.THUNDERSTORM,
  125: ColorCode.THUNDERSTORM,
  126: ColorCode.THUNDERSTORM,
  127: ColorCode.THUNDERSTORM,
  128: ColorCode.THUNDERSTORM,
  130: ColorCode.THUNDERSTORM,
  131: ColorCode.THUNDERSTORM,
  132: ColorCode.THUNDERSTORM,
  133: ColorCode.THUNDERSTORM,
  134: ColorCode.THUNDERSTORM,
  135: ColorCode.THUNDERSTORM,
  136: ColorCode.THUNDERSTORM,
  137: ColorCode.THUNDERSTORM,
  138: ColorCode.THUNDERSTORM,
  140: ColorCode.THUNDERSTORM,
  141: ColorCode.THUNDERSTORM,
  142: ColorCode.THUNDERSTORM,

  210: ColorCode.RAIN,
  211: ColorCode.RAIN,
  212: ColorCode.RAIN,

  220: ColorCode.SNOW,
  221: ColorCode.SNOW,
  222: ColorCode.SNOW,

  230: ColorCode.SNOW,
  231: ColorCode.SNOW,
  232: ColorCode.SNOW,

  235: ColorCode.HAIL,
};

// Permet à l'api de savoir les données à récupèrer
enum When { NOW, HOURLY, DAILY }

// Pour convertir les jours de la semaine
const Map<int, String> dayTable = {
  1: "Lun",
  2: "Mar",
  3: "Mer",
  4: "Jeu",
  5: "Ven",
  6: "Sam",
  7: "Dim",
};

// Quelques valeurs pré enregistré de villes
const Map<String, String> cityTable = {
  "2A004": "Ajaccio",
  "13001": "Aix-en-Provence",
  "81004": "Albi",
  "80021": "Amiens",
  "49007": "Angers",
  "74010": "Annecy",
  "06004": "Antibes",
  "13004": "Arles",
  "84007": "Avignon",
  "2B033": "Bastia",
  "14047": "Bayeux",
  "25056": "Besançon",
  "64122": "Biarritz",
  "33063": "Bordeaux",
  "29019": "Brest",
  "06029": "Cannes",
  "11069": "Carcassonne",
  "73065": "Chambéry",
  "28085": "Chartres",
  "63113": "Clermont-Ferrand",
  "68066": "Colmar",
  "21231": "Dijon",
  "14220": "Deauville",
  "38185": "Grenoble",
  "17300": "La Rochelle",
  "76351": "Le Havre",
  "59350": "Lille",
  "69388": "Lyon",
  "13055": "Marseille",
  "57463": "Metz",
  "34172": "Montpellier",
  "31395": "Muret",
  "54395": "Nancy",
  "44109": "Nantes",
  "06088": "Nice",
  "30189": "Nîmes",
  "75056": "Paris",
  "64445": "Pau",
  "66136": "Perpignan",
  "51454": "Reims",
  "35238": "Rennes",
  "76540": "Rouen",
  "42218": "Saint-Étienne",
  "35288": "Saint-Malo",
  "83119": "Saint-Tropez",
  "34301": "Sète",
  "67482": "Strasbourg",
  "83137": "Toulon",
  "31555": "Toulouse",
  "37261": "Tours",
  "78646": "Versailles",
};
